name: CI / CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: penjadwalan
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: xdebug

      - name: Install backend dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Set DB credentials in .env
        run: |
          php -r "file_put_contents('.env', str_replace('DB_HOST=127.0.0.1', 'DB_HOST=127.0.0.1', file_get_contents('.env')));"
          php -r "file_put_contents('.env', str_replace('DB_DATABASE=homestead', 'DB_DATABASE=penjadwalan', file_get_contents('.env')));"
          php -r "file_put_contents('.env', str_replace('DB_USERNAME=homestead', 'DB_USERNAME=root', file_get_contents('.env')));"
          php -r "file_put_contents('.env', str_replace('DB_PASSWORD=secret', 'DB_PASSWORD=root', file_get_contents('.env')));"

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: vendor/bin/phpunit --testdox

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: backend-tests
    if: ${{ always() }}   # tetap jalankan, tapi bisa diubah

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
